### ISSUE TITLE
Ruby 2.3.1 openssl

### ISSUE THREAD

**Issue by denisemauldin** [rbenv/ruby-build#1006]
Hi all,

I'm trying to build ruby 2.3.1 on linux 2.6.32-642.1.1.el6.x86_64 and I'm running into errors with openssl.  I've tried building with rvm and I've tried building separately, but I can't figure out which version of openssl is supposed to be supported with ruby 2.3.1.  I've installed openssl 1.0.2-beta3, openssl 1.0.2.j and openssl 1.1.0b and none of them seem to be working.  They all give error:

> configuring openssl
> Ignore OpenSSL broken by Apple.
> Please use another openssl. (e.g. using `configure --with-openssl-dir=/path/to/openssl')
> Failed to configure openssl. It will not be installed.

When I force it past that issue, it then won't run gem commands because it gives an SSL error.  I'm not sure what to do here, so advice please?  Sorry if this is the wrong repo to ask this.  Let me know a more appropriate one if possible.  Thanks.

**Comment by mislav** [comment]
Hello @denisemauldin,

Which command did you use to install Ruby 2.3.1? If it was `rvm install`, then you might be commenting on the wrong project, since RVM is not related to us at all. if it was `rbenv install` or `ruby-build`, on the other hand, then you're at the right place.

I'm not sure why you're getting these openssl failures. Ruby 2.3.1 should work with 1.0.2g and 1.0.2h in our experience, and that means that 1.0.2j should also probably work. Have you tried locating your openssl install and passing a path to it using `--with-openssl-dir` like the error message suggested?

One confusing thing is that the configure script complained about "Ignore OpenSSL broken by Apple", but you're not on macOS at all. It sounds like the configure script might have gotten confused by something at this point, but I'm not sure what. /cc @hsbt

**Comment by hsbt** [comment]
Ruby 2.3.1 is not works with OpenSSL-1.1.0. This feature is after Ruby 2.4.0.

And I wondered why this error was displayed on linux environment.

**Comment by denisemauldin** [comment]
Thanks! I blew away everything and installed 1.0.2j and it works now.  I think 1.1.0b was the previous one I'd had installed.

**Comment by tirthajyoti-ghosh** [comment]
### Try this [blog](https://www.garron.me/en/linux/install-ruby-2-3-3-ubuntu.html). It helped me.

I had the same problem when I tried this `rbenv install 2.3.8`

I faced the same `The Ruby openssl extension was not compiled.` error. After searching through the internet, I came across this [blog](https://www.garron.me/en/linux/install-ruby-2-3-3-ubuntu.html). 

#### Reason:
Ruby < 2.4 is not compatible with openssl 1.1, so, you need libssl1.0-dev, hence the solution.
