### ISSUE TITLE
Failed to download jruby-9.2.0.0-dev

### ISSUE THREAD

**Issue by sandelius** [rbenv/ruby-build#1131]
```
Downloading jruby-bin-9.2.0.0-SNAPSHOT.tar.gz...
-> http://ci.jruby.org/snapshots/master/jruby-bin-9.2.0.0-SNAPSHOT.tar.gz
error: failed to download jruby-9.2.0.0-SNAPSHOT.tar.gz

BUILD FAILED (OS X 10.12.6 using ruby-build 20170726-17-g0ae5281)
```

Perhaps I should file this under jruby?

**Comment by alexanderadam** [comment]
I have the same issue with every other ruby version as well:

```bash
$ rbenv install 2.4.2
Downloading ruby-2.4.2.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.bz2
error: failed to download ruby-2.4.2.tar.bz2

BUILD FAILED (Ubuntu 17.04 using ruby-build 20170914)
```

You can see more details when you use `-v` switch (ie. `rbenv install 2.4.2 -v`).

In my case the source of the problem was the usage of `aria2`. Because it seems that there is an async DNS options that [seem to fail sometimes](https://github.com/aria2/aria2/issues/774#issuecomment-330499293).

I was able to solve this for me by disabling it with the aria2 option `--async-dns=false`. So for example:
```bash
$ RUBY_BUILD_ARIA2_OPTS=--async-dns=false rbenv install 2.4.2 -v
```

It would be nice however if the next http client would be used if the first client failed (so use `wget` or `curl` if `aria2` fails).

**Comment by sandelius** [comment]
@alexanderadam The jruby issue is that their packages has been removed from s3 and they're investigating it. I get 404
