### ISSUE TITLE
Automatically select first installed version as global

### ISSUE THREAD

**Issue by sunkup** [rbenv/ruby-build#1209]
How about automatically selecting the first installed ruby version as global, so the first time setup becomes even easier? 

Many people seem to [forget that](https://github.com/rbenv/rbenv/issues/1094#issuecomment-396259530).

**Comment by jasonkarns** [comment]
Personally, that would conflict with my usage of rbenv and nodenv. I keep my system ruby and system node up to date with homebrew, so "system" is always the latest version. I use rbenv and nodenv to have pinned versions for projects. In my usage, automatically selecting the first installed version would be quite counter productive, as not only would it obscure my system ruby/node, it would be pinned to (eventually) the oldest runtime on my system.

**Comment by extremesonic** [comment]
hmm yeah, no chance then.

**Comment by mislav** [comment]
Reopening to reconsider this per https://github.com/rbenv/rbenv/issues/1424

@jasonkarns I wouldn't automatically select the newly installed version to keep backwards compatibility, but upon installing the first Ruby version using rbenv and if no global version is already selected, do you think `rbenv install` could at least print a suggestion to run `rbenv global <VERSION>`, since I presume most people will want to do that to avoid accidentally trying to install gems into the system version?

**Comment by mislav** [comment]
Fixed in https://github.com/rbenv/ruby-build/pull/2052
