### ISSUE TITLE
Please make a new release with MRI 2.5.5 included

### ISSUE THREAD

**Issue by arpitchauhan** [rbenv/ruby-build#1291]
Though MRI 2.5.5 has been added to master, a new release hasn't been made. It'd be very helpful if that was done. Thanks! :)

**Comment by KsRyY** [comment]
The pull request #1289 is already merged to the master branch

**Comment by arpitchauhan** [comment]
Yeah, but I meant that a new release hasn't been made after that PR was merged into master. https://github.com/rbenv/ruby-build/releases

**Comment by aitor** [comment]
Yes, please make a release. Then we can update the ruby-build brew formula and let homebrew users install the new version that fixes [an important deadlock](https://www.ruby-lang.org/en/news/2019/03/15/ruby-2-5-5-released/).

**Comment by dazuma** [comment]
Calling @hsbt

**Comment by hsbt** [comment]
I know this. But the homebrew formula is NOT our responsibility. because the initial commit is the other contributor. 

Do not rush us.

**Comment by aitor** [comment]
I’m sorry if I’ve made you feel rushed. 

I didn’t imply the formula was your responsibility, just that it is not possible to update it until a new release is made. Given the PR has been already merged I thought it may be easy to do the release. 

> because the initial commit is the other contributor.

I’m not sure what you mean with this. Who is “the other contributor” and which is “the initial commit”?

**Comment by hsbt** [comment]
see. https://github.com/Homebrew/homebrew-core/commit/f7cbbefb3d7f2fdaff7c17b15104b1730bf5448b

I (and the current maintainers) are surprised to request to maintain its formula from homebrew users at first. Therefore, the maintaining of homebrew formula is totally spare time work for me.

**Comment by dazuma** [comment]
@hsbt I'm sorry I was not clear. I'm not asking you to maintain the homebrew formula. I'm just asking for a release of ruby-build that includes 2.5.5 (maybe just another commit like https://github.com/rbenv/ruby-build/commit/2ecfe4d42a032a73ee4a8ba6b4a43de4512ffbe4). Then other people who are working on other tools can update their code to point to the new release. Thanks!

**Comment by hsbt** [comment]
I understood the 3rd party tools used a release tag. But they are also the out of our development scope same as homebrew.

In the background, I'm also a member of ruby core team. We have a plan to release other versions soon. Because the release tag is made by my convenience. I do not want to do release work every time.

**Comment by aitor** [comment]
> I'm not asking you to maintain the homebrew formula. I'm just asking for a release of ruby-build that includes 2.5.5 (maybe just another commit like 2ecfe4d)

Exactly. That's why I offered to PR both changes. Now that I've inspected the repo I see that actually `script/release` will actually take care of almost all(?) the changes:

```
# - checks out the master branch
# - changes version in `bin/ruby-build` to current date
# - commits and tags the change
# - pushes master + tag to GitHub
# - opens pull request to update the Homebrew formula
```

In any case, please let us know if/how we can help.

> I understood the 3rd party tools used a release tag. But they are also the out of our development scope same as homebrew.

Not only that but homebrew **is the recommended install option** for all macOS users. I understand that by specifically recommending that "3rd party tool"  both in `ruby-build` and in `rbenv` a tighter relation is created between both projects.

> In the background, I'm also a member of ruby core team. We have a plan to release other versions soon. Because the release tag is made by my convenience.

I see. I think access to the new version is good and moderately important given the security patches but, again, I don't to impose or rush, so please feel free to close the ticket.

**Comment by hsbt** [comment]
> I don't to impose or rush, so please feel free to close the ticket.

Thank you for your understanding. I'm going to release the next version of ruby-build after releasing the stable version of Ruby.

**Comment by robertosante** [comment]
when is this going to be updated?

**Comment by icantrap** [comment]
@hsbt Can you clarify?
>I'm going to release the next version of ruby-build after releasing the stable version of Ruby.

Isn't 2.5.5 the stable version of Ruby?

http://ruby-lang.org lists versions 2.6.2, 2.5.5, and 2.4.5 as the stable versions of Ruby. The front page has announcement posts for 2.5.5 and 2.6.2.

**Comment by hsbt** [comment]
Again, Do not rush us.

**Comment by hsbt** [comment]
Just released: https://github.com/rbenv/ruby-build/releases/tag/v20190320
