### ISSUE TITLE
Debian Stretch package is very old

### ISSUE THREAD

**Issue by mawise** [rbenv/ruby-build#1374]
Hi,

I'm setting up a raspberry pi to host a rails application using rbenv and passenger (context).  I'd like to use the Debian (stretch) packages for `rbenv` and `ruby-build`, but it provides a very old (2016) version of ruby-build with outdated definitions.  There is no version of ruby newer than 2.4.0

It would be great if the package-installed version of ruby-build could dynamically update it's definitions, or we could periodically (annually?) update the version provided for system packages.  

Debian buster has a 2017 version of ruby-build which should also be updated.  Passenger doesn't yet support buster, hence my interest in stretch.

**Comment by mislav** [comment]
Hi thank you for bringing this to our attention.

Like many packages, `ruby-build` for Debian isn't built by us (the project maintainers), but by someone else from the Debian community. To get the package updated, you will have to track down who that was and reach out to them directly.

In the meantime, install the latest version of ruby-build from git:

```
git clone https://github.com/rbenv/ruby-build ~/.rbenv/plugins/ruby-build
```

**Comment by DaAwesomeP** [comment]
This seems to be an issue again (now for Debian Bullseye). It might be worth noting this in the README.

**Comment by mislav** [comment]
@DaAwesomeP Thanks for letting us know. Again, we do not list the debian package as an installation method in our README, therefore it's not our responsibility to point out that the debian package is not maintained by us and that it could be out of date. You absolutely would not want to install ruby-build via debian package because ruby-build tends to have updates often, while debian is generally conservative (i.e. slow) when updating packages in its repository.

**Comment by DaAwesomeP** [comment]
My bad, I got the repos mixed up: the rbenv README instructs to install from the Debian repo. This in turn installs ruby-build from the Debian repo. I should open an issue there.
