### ISSUE TITLE
build failed (Ubuntu 19.10 using ruby-build)

### ISSUE THREAD

**Issue by artoodeeto** [rbenv/ruby-build#1396]
Hello can you help me? Ive update my `PopOS` to version 19.10 but for some reason my rbevn got affected, so I have uninstalled and installed `rbenv` but that doesnt work. If been checking out google and SO but theres no luck. can you point me to right direction here? im so lost. 

```rbenv install 2.3.6
Downloading ruby-2.3.6.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.6.tar.bz2
Installing ruby-2.3.6...
 
BUILD FAILED (Ubuntu 19.10 using ruby-build 20191225-1-gbac1f1c)

Inspect or clean up the working tree at /tmp/ruby-build.20200109092953.29867.yABTeW
Results logged to /tmp/ruby-build.20200109092953.29867.log

Last 10 log lines:
linking shared-object pathname.so
make[2]: Leaving directory '/tmp/ruby-build.20200109092953.29867.yABTeW/ruby-2.3.6/ext/pathname'
linking shared-object bigdecimal.so
make[2]: Leaving directory '/tmp/ruby-build.20200109092953.29867.yABTeW/ruby-2.3.6/ext/bigdecimal'
linking shared-object nkf.so
make[2]: Leaving directory '/tmp/ruby-build.20200109092953.29867.yABTeW/ruby-2.3.6/ext/nkf'
linking shared-object date_core.so
make[2]: Leaving directory '/tmp/ruby-build.20200109092953.29867.yABTeW/ruby-2.3.6/ext/date'
make[1]: Leaving directory '/tmp/ruby-build.20200109092953.29867.yABTeW/ruby-2.3.6'
make: *** [uncommon.mk:203: build-ext] Error 2
```

**Comment by Chagchen** [comment]
I have issue installing brenv - ruby-build on ubuntu. I choose not to use the yarn package form gorails as I use nvm with node. Yarn caused issues with npm -g packages.  the solution below didn't fix the issue. Running Ubuntu 19.10.


rbenv install 2.7.0
Downloading ruby-2.7.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.0.tar.bz2
Installing ruby-2.7.0...

BUILD FAILED (Ubuntu 19.10 using ruby-build 20200115-8-g73b926b)

Inspect or clean up the working tree at /tmp/ruby-build.20200124125903.3740.8URNN9
Results logged to /tmp/ruby-build.20200124125903.3740.log

Last 10 log lines:
                                    minitest 5.13.0
The Ruby zlib extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Try running `apt-get install -y zlib1g-dev` to fetch missing dependencies.

Configure options used:
  --prefix=/home/fifthavecode/.rbenv/versions/2.7.0
  --enable-shared
  LDFLAGS=-L/home/fifthavecode/.rbenv/versions/2.7.0/lib 
  CPPFLAGS=-I/home/fifthavecode/.rbenv/versions/2.7.0/include

**Comment by artoodeeto** [comment]
thanks for the response but I fixed this by following https://github.com/rbenv/ruby-build/wiki#openssl-usrincludeopensslasn1_mach102-error-error-this-file-is-obsolete-please-update-your-software or downgrading ssl. thanks

**Comment by fabien-qe** [comment]
I got this too because I try to install [ruby 2.3 which is not ok with openssl 1.1](
https://github.com/rbenv/ruby-build/wiki#openssl-version-compatibility)
