### ISSUE TITLE
macOS Migration Assistant Causing Install Failures

### ISSUE THREAD

**Issue by cglusky** [rbenv/ruby-build#1406]
Just getting into with installing Brew/Ruby/Gems etc for Jekyll support.

Had no end of issues getting things installed and it looks like it is related to a mac that has been migrated creating some header files in user/local/include.  Or bad symlinks.  Or???

I would resolve one error only to have another pop up.  After renaming my includes folder and creating another with permissions all of my issues went away.  Including needing to try to use options to point to brew ssl.  I am down to only needing...

`rbenv install 2.7.0 `

My suggestion is to document use of brew doctor as that is what helped me the most.  It even helps with recreation of include folder.

Per this thread (and a few similar):

https://github.com/pyenv/pyenv/issues/448#issuecomment-382894402

**Comment by mislav** [comment]
Thank you for letting us know! Transferred to ruby-build repo.

I'm not sure what you're asking us to improve in rbenv/ruby-build though. Is there something that is a bug of this library that needs to be fixed? We certainly won't ask users to rename their `/usr/local/include` or similar, since I see that as a nuclear option that should only be done if someone's machine is in an unsalvagable state.

**Comment by cglusky** [comment]
Add a few troubleshooting tips for user who have used migration assistant?  I agree that renaming /usr/local/include is a bit nuclear but for a barbarian hacker like me it did work.  I did try targeting offending files but it seemed like I was not making much progress.  So I renamed the folder and all was fixed.  For me.

**Comment by mislav** [comment]
@cglusky You may add a section for this under [Troubleshooting in our wiki](https://github.com/rbenv/ruby-build/wiki#troubleshooting).

Remember that the best troubleshooting advice contains the original error message that you got while building, because people will search for that error message and a solution for it. They might not remember that they've used Migration assistant before, or they might not make a connection that it was the assistant that caused their issues, so they might not search for "migration assistant" in the first place.

Thank you!
