### ISSUE TITLE
rbenv install 2.3.6 install failed - MacOs Big Sur

### ISSUE THREAD

**Issue by somasekhar** [rbenv/ruby-build#1720]
~ CFLAGS="-Wno-error=implicit-function-declaration" rbenv install 2.3.6

Downloading ruby-2.3.6.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.6.tar.bz2
Installing ruby-2.3.6...

WARNING: ruby-2.3.6 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.

ruby-build: using readline from homebrew

BUILD FAILED (macOS 11.1 using ruby-build 20210119)

Inspect or clean up the working tree at /var/folders/gn/vxb82ht51wj99_ccmk4jz48m0000gn/T/ruby-build.20210210111336.50721.WxpYJV
Results logged to /var/folders/gn/vxb82ht51wj99_ccmk4jz48m0000gn/T/ruby-build.20210210111336.50721.log

Last 10 log lines:
The Ruby openssl extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Configure options used:
  --prefix=/Users/admin/.rbenv/versions/2.3.6
  --with-openssl-dir=/opt/homebrew/opt/openssl@1.1
  --with-readline-dir=/opt/homebrew/opt/readline
  CC=clang
  CFLAGS=-Wno-error=implicit-function-declaration
  LDFLAGS=-L/Users/admin/.rbenv/versions/2.3.6/lib -L/Users/admin/.rbenv/versions/2.3.6/lib -L/opt/homebrew/opt/readline/lib
  CPPFLAGS=-I/Users/admin/.rbenv/versions/2.3.6/include -I/Users/admin/.rbenv/versions/2.3.6/include -I/opt/homebrew/opt/readline/include

**Comment by SVynnytska** [comment]
I have the same issue `BUILD FAILED (macOS 11.2.1 using ruby-build 20210119)`
`Last 10 log lines:
ERROR: Ruby install aborted due to missing extensions
Configure options used:
  --prefix=/Users/myuser/.rbenv/versions/2.7.1
  --with-openssl-dir=/opt/local
  --enable-shared
  --with-readline-dir=/usr/local/opt/readline
  CC=clang
  CFLAGS=-I/usr/local/include/
  LDFLAGS=-L/Users/myuser/.rbenv/versions/2.7.1/lib -L/usr/local/opt/openssl/lib
  CPPFLAGS=-I/Users/myuser/.rbenv/versions/2.7.1/include -I/usr/local/opt/openssl/include`

**Comment by hsbt** [comment]
I could install Ruby 2.3.8 on macOS Big Sur 11.2. There is no fails.
