### ISSUE TITLE
Can the install command have --verbose by default

### ISSUE THREAD

**Issue by vamsipavanmahesh** [rbenv/ruby-build#1721]
When I run the install command:
It just shows "Installing ruby-3.0.0..."
But the end-user has no idea of whether there is progress being made, oftentimes they feel they are stuck
Context: https://stackoverflow.com/a/25210537/1395129

I think a quick solution to fix this is, making the default behavior of the install command show verbose logs

**Comment by jaydorsey** [comment]
Would love this as well. Something changed semi-recently (I think with ruby-build, but I'm also using asdf-ruby so maybe there) were I no longer get output. I'm unable to figure out the correct set of flags to pass thru to get ruby-build to show verbose output (for debugging why readline isn't being picked up)

**Comment by eregon** [comment]
I think it's hard to change the default. The whole build output is a lot lot of output, I doubt that is useful.
The `...` should make it clear the user needs to wait, it's the same e.g. when installing a C extension.

**Comment by jaydorsey** [comment]
It's been a while since I've run into this, but if I remember correctly the reason for this request (at least my reason for chiming in) was that the build was getting stuck on something, and wouldn't show any debug information.

This made it very hard to debug failures to build when things like openssl wasn't setup correctly, because it wouldn't spit any errors out.

**Comment by Tundratrot** [comment]
I am experiencing the same problem. The build is stuck and I have no idea why. I don't know if I should be waiting or what.

**Comment by jaydorsey** [comment]
> I am experiencing the same problem. The build is stuck and I have no idea why. I don't know if I should be waiting or what.

If I remember correctly, the way I found the root cause was by inspecting the ruby-build helper in asdf (`$HOME/.asdf/plugins/ruby/ruby-build/bin/ruby-build`) or the `lib/utils.sh` file and just doing puts debugging (adding echo statements at various places until I found the error)

**Comment by eregon** [comment]
I have never seen a hang during building Ruby, so I think this is then mostly an issue about "how to find out what it's doing on slow machines when building Ruby?".
I think an easy way to address is to print the log and let people look at the log if they feel it takes too long, I'll make a PR for that.

**Comment by jaydorsey** [comment]
> I think this is then mostly an issue about "how to find out what it's doing on slow machines when building Ruby?"

When I first encountered this issue I was on a relatively new M1 macbook.

The actual scenario is a little bit hazy because it's been a while, but I believe it was related to [this comment](https://github.com/rbenv/ruby-build/issues/1388#issuecomment-785459881) where jemalloc args weren't being recognized as expected, and the ruby build was hanging due to an error finding jemalloc and/or gmp because the flags I was using didn't behave the same (details in that PR).

> I think an easy way to address is to print the log and let people look at the log if they feel it takes too long, I'll make a PR for that.

Thank you for this!
