### ISSUE TITLE
Consider removing AWS_ACCESS_KEY_ID from mirror workflow

### ISSUE THREAD

**Issue by udondan** [rbenv/ruby-build#1992]
In the file [/master/.github/workflows/mirror.yml#L25](https://github.com/rbenv/ruby-build/blob/master/.github/workflows/mirror.yml#L25) you expose your AWS_ACCESS_KEY_ID.

Apart from the fact that this _might_ be a security concern, this is causing problems on user end when scanning with security tools. For example the popular vulnerability scanner [Trivy](https://github.com/aquasecurity/trivy) is raising a critical error.

![CleanShot 2022-07-05 at 09 04 00](https://user-images.githubusercontent.com/6443408/177269456-34ce5fe4-3528-40fe-82c5-74c645d8941c.png)

Would be great if you could move the value to a github secret, just like the `AWS_SECRET_ACCESS_KEY`.

**Comment by mislav** [comment]
Thanks for raising this issue. I won't, however, move this to a secret just because a vulnerability tool considers this a critical error:
- The key is already in git. Moving it to a "secret" does not obfuscate it in any way since it doesn't remove it from git history;
- Knowing someone's access key ID can cause no damage, and is in fact no vulnerability in it of itself.

You could try configuring your scanner so it [doesn't consider this a critical error](https://github.com/aquasecurity/trivy/blob/e77cfd6487cbd79e4f14e435186a7ac9d8888d5d/pkg/fanal/secret/builtin-rules.go#L81-L87).

**Comment by mislav** [comment]
Update: the AWS access key is now gone from version control
