### ISSUE TITLE
Nothing is building on Ubuntu 20.04 with OpenSSL 1.1.1f libraries

### ISSUE THREAD

**Issue by hackdefendr** [rbenv/ruby-build#2081]
### Steps to reproduce the behavior
1. Install all required dependency packages for Ubuntu 20.04
2. Install rbenv and ruby-build plugin
3. Standard build for ruby 3.0.4 fails due to incompatibility in SSL libraries.

### Expected vs. actual behavior
1. In June of this year I was able to build Ruby v3.0.3 and several rubies/gems etc.
2. In November, present day, absolutely nothing ruby will build
3. My mastodon server is currently hosed because of this issue.
4. I expect the build process to be successful

### Logs
[https://gist.github.com/hackdefendr/0843d822fbfbecdc777b007bbe82aea8](https://gist.github.com/hackdefendr/0843d822fbfbecdc777b007bbe82aea8)

### Notes
There seems to be a few discussions around build failures on Ubuntu, but no actual solutions are being suggested.

**Comment by hackdefendr** [comment]
### Update
1. Upgraded my host to Ubuntu 22.04.1
2. Same issue, nothing is building

**Comment by phylor** [comment]
I had [some issues on ArchLinux](https://aur.archlinux.org/packages/ruby-build#comment-888512), but not the same error as @hackdefendr.

Maybe you need to use another gcc version. I'm not currently using Ubuntu though.

You could try with something like:

```
apt install gcc-10
CC=/usr/bin/gcc-10 rbenv install 3.0.3
```

Really a shot in the dark though.

**Comment by hackdefendr** [comment]
I gave it a shot, but unfortunately got the same errors. I think this is due to the latest change from patching an OpenSSL vulnerability. Something was introduced in that patch that is causing every single Ruby compile that has SSL dependencies to crash.

**Comment by mislav** [comment]
@hackdefendr Sorry that you're experiencing trouble. ruby-build does nothing to ensure OpenSSL compatibility, therefore this isn't a sign of breakage in ruby-build and this report should be moved to the Discussion area instead. You need to have a compatible OpenSSL version installed on your system in order to build Ruby. You can download and compile your own OpenSSL if all else fails and link to it using `RUBY_CONFIGURE_OPTS="--with-openssl-dir=/path/to/openssl"`

**Comment by hackdefendr** [comment]
Please re-open this and do a better investigation.

--with-openssl-dir is not a Ruby configure option anymore. 

I do have the correct SSL libraries installed already as I did in June when this worked. Based on other discussions, you aren't addressing any of the complaints there either. This absolutely is an issue with the ruby-build process.

Please stop telling people to use discussions because nobody is discussing anything.

**Comment by phylor** [comment]
On ArchLinux the following works for me to build Ruby today:

```
PKG_CONFIG_PATH=/usr/lib/openssl-1.1/pkgconfig rbenv install 3.1.2
```

Also had to install openssl-1.1, because ArchLinux uses v3 currently.

No idea if that helps you on Ubuntu though.

It would of course be great if ruby-build was smart enough to search for openssl versions or at least notify with a better error message which openssl version is required. With openssl-1.0 builds also fail.

**Comment by hackdefendr** [comment]
@mislav please re-open this as a bug. It may be a bug with openssl,  but it is impacting everything Ruby with a dependency to it to fail.
