### ISSUE TITLE
If a file named after the Ruby version exists in the pwd, ruby-build executes that file instead of installing the version

### ISSUE THREAD

**Issue by monfresh** [rbenv/ruby-build#2153]
### Steps to reproduce the behavior
1. `rbenv uninstall 3.1.3`
1. `cd` into any directory
2. `echo 'echo "hello from a file called 3.1.3"' >> 3.1.3`
3. `rbenv install 3.1.3` or `ruby-build 3.1.3 ~/.rbenv/versions/3.1.3`

### Expected vs. actual behavior
Expected behavior: the fact that a file with the same name as the desired Ruby version exists in the pwd should have no impact on the Ruby installation.

Actual behavior: ruby-build will execute any commands in the file, which could potentially result in unintended destructive behavior. Here's the output:
```
To follow progress, use 'tail -f /var/folders/w9/yj7qtv7d7llb0k21b3mplnhh0000gn/T/ruby-build.20230223120613.23152.log' or pass --verbose
hello from a file called 3.1.3
```
With `rbenv install 3.1.3`, it thinks the installation passed because of the exit status of executing the `3.1.3` file:
```
To follow progress, use 'tail -f /var/folders/w9/yj7qtv7d7llb0k21b3mplnhh0000gn/T/ruby-build.20230223120613.23152.log' or pass --verbose
hello from a file called 3.1.3

NOTE: to activate this Ruby version as the new default, run: rbenv global 3.1.3
```

If the file starts with a line that isn't a valid command, then it will fail due to "command not found":
```
To follow progress, use 'tail -f /var/folders/w9/yj7qtv7d7llb0k21b3mplnhh0000gn/T/ruby-build.20230223125047.15428.log' or pass --verbose
3.1.3: line 1: hello: command not found

BUILD FAILED (macOS 13.2.1 using ruby-build 20230222)
```

**Comment by jasonkarns** [comment]
This is intentional behavior and documented in the usage of these commands:

```
$ rbenv install -h
Usage: rbenv install [-f|-s] [-kpv] <version>
       rbenv install [-f|-s] [-kpv] <definition-file>
```
```
$ ruby-build -h
ruby-build 20230202

Usage: ruby-build [-kpv] <definition> <prefix>
```

The `<definition-file>`/`<definition>` is the argument here. The behavior is desired for creating custom build-definition files and installing custom builds. (No joke, I did this just today in order to get a build of ruby that uses a FIPS-enabled openssl).

To be clear, the filename itself matching any given ruby version is incidental. The `<definition>/<definition-file>` argument is simply a path to a file. As a _fallback_, that argument is matched against files that it finds in `RUBY_BUILD_DEFINITIONS` directories; which just so happen to normally be named after ruby versions. (The default `RUBY_BUILD_DEFINITIONS` path including ruby-build's own [`share/ruby-build/`](https://github.com/rbenv/ruby-build/tree/master/share/ruby-build) directory.)

I do see the potential for some confusion here. And it might make sense for ruby-build to expect a prefix (`./`) when matching files outside of `RUBY_BUILD_DEFINITIONS`. Perhaps a feature request?

**Comment by monfresh** [comment]
Thanks for the explanation. It makes sense, though I still find it surprising. I would expect the default behavior to only use definitions in `RUBY_BUILD_DEFINITIONS` directories. Additionally, it would be nice for the definition to be validated. For example, if it doesn't include `install_package`, then it should exit with an appropriate error message. 

Just a suggestion though. Perhaps someone with more time can take a stab at implementing it. Feel free to close this issue.

**Comment by mislav** [comment]
> Additionally, it would be nice for the definition to be validated. For example, if it doesn't include `install_package`, then it should exit with an appropriate error message.

Since definition files are just shell scripts invoking ruby-build functions, I'm not sure what kind of validation we could perform, since these scripts can contain anything (they don't necessarily have to invoke `install_package`).

I understand that this is confusing, but because people normally don't have matching unrelated files called `X.Y.Z` in their current directory, this isn't something that many people will run into. If we were designing this functionality from scratch today, we could require that referencing a local file must start with `./` in the argument name, like @jasonkarns suggested, but we can't introduce that requirement now because it would break backwards compatibility with scripts.

Since I'm lacking concrete ideas to improve this that would also be safe to implement, and since I don't believe the risk of this confusion is great, I will close this. Thanks for the discussion!
