### ISSUE TITLE
Automatically link to Homebrew openssl

### ISSUE THREAD

**Issue by mislav** [rbenv/ruby-build#2157]
I think it would make sense to default to Homebrew's openssl@correctVersion if it's installed. It would be consistent with readline, gmp and libyaml. And also because Homebrew's openssl works for using any extension which uses a Homebrew formula which links against libssl, unlike the custom-built openssl (which would cause to load 2 libssl in the same process, which usually doesn't work well).

_Originally posted by @eregon in https://github.com/rbenv/ruby-build/issues/2023#issuecomment-1456819753_

* * *

In the past we avoided setting `--with-openssl-dir` by default to link to Homebrew's OpenSSL because we were not sure if this is what the user wanted or desired, and because ruby-build will automatically download and compile the correct version of openssl if system openssl is missing (or broken on macOS).

However, we find ourselves suggesting to our users to manually set RUBY_CONFIGURE_OPTS to link to Homebrew's openssl so often, that it could as well be a built-in feature. The benefits are:
- **Faster build times.** A separate version of openssl now doesn't have to be compiled per each Ruby version, and `brew install openssl` is fast due to it being “bottled”.
- **Not having to know** which `openssl@VERSION` to link to. Currently, we have to explain to people to manually link to `openssl@1.1` for older Rubies and to `openssl@3` for newer. As new OpenSSL versions keep being released in the future, if would be a relief to our users that they don't have to keep track of compatibility.
- **Keep openssl upgraded.** Doing `brew upgrade openssl` will keep it upgraded for any Ruby version linked to it.

In the past, we did try to automatically link to Homebrew's openssl, but we hardcoded that to `openssl@1.1` for all Ruby versions which naturally caused troubles, so it had to be reverted: https://github.com/rbenv/ruby-build/pull/1375. If we brought back the feature, we would have to dynamically choose `openssl@VERSION` depending on Ruby version.

**Comment by dbackeus** [comment]
Just to point out an issue with relying on brews libraries: historically brew has had a tendency of bricking mine and my colleagues Ruby installations by automatically upgrading and removing older versions of libraries, which has then broken the dynamic linking.

Perhaps the best of all worlds would be to default to using locally pre-existing libraries, but make copies of them into `~/.rbenv` somewhere to ensure that Ruby installations are not subject to dynamic linking failures once installed?

**Comment by dentarg** [comment]
On that topic, I think `export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1` have probably helped me in this regard.

> Unless `HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK` is set, `brew upgrade` or `brew reinstall` will be run for outdated dependents ... – _https://docs.brew.sh/Manpage#install-options-formulacask-_

**Comment by eregon** [comment]
Is there an Homebrew issue about this or a more precise description? It sounds like a bug.

Is the problem that during linking it embeds an absolute path to a specific exact version of openssl instead of linking to e.g. `/opt/homebrew/opt/openssl@3/lib/libssl.so.3`?

I wish Homebrew would place its libraries inside the system library path then everything might just work... (it doesn't since aarch64, and macOS gives no way to extend the library path)

**Comment by akierig** [comment]
I was just about to check if there was a similar issue or PR for MacPorts OpenSSL.

> Perhaps the best of all worlds would be to default to using locally pre-existing libraries, but make copies of them into ~/.rbenv somewhere to ensure that Ruby installations are not subject to dynamic linking failures once installed?

this seems like a good solution except I'd suggest not defaulting to `~/.rbenv` but checking if `RBENV_ROOT` is set.

**Comment by dentarg** [comment]
What does rbenv has to do with ruby-build? I'm only using ruby-build, not rbenv (so I don't have `~/.rbenv` or `RBENV_ROOT` set).

**Comment by eregon** [comment]
> Perhaps the best of all worlds would be to default to using locally pre-existing libraries, but make copies of them into `~/.rbenv` somewhere to ensure that Ruby installations are not subject to dynamic linking failures once installed?

I would be very uncomfortable with that. If using the "system openssl" (i.e., from Homebrew or MacPorts, that's the closest thing to system on macOS since there is no system package manager), then it should actually use that in its standard location, not a copy. I think copying is likely to cause all sorts of problems if there is any relative link in the library.
I guess with the soname at least the library wouldn't be loaded twice, but then it would be pretty surprising if something linked against the "system openssl" but then wouldn't load it because that copy is loaded. And of course it would waste some disk space.

At least I believe we need to understand precisely what is the problem with Homebrew and what solutions are possible before doing such heavy workarounds.
