### ISSUE TITLE
Add option to not link against Homebrew openssl

### ISSUE THREAD

**Issue by brandonfriess-stripe** [rbenv/ruby-build#2319]
It seems that ruby-build has decided to link against Homebrew openssl again in https://github.com/rbenv/ruby-build/pull/2275.

This is a bit puzzling, considering the project opted to _not_ link against Homebrew openssl in https://github.com/rbenv/ruby-build/pull/1375.

I much preferred the prior logic to keep openssl self-contained to the ruby version installed on the system. This prevents a bunch of issues with Homebrew user's (or the project) making changes to brew installed openssl versions that may break their ruby installs [0].

Perhaps we can strike a balance here to let ruby build users choose between linking to Homebrew openssl or let ruby-build handle compiling a per-Ruby version of OpenSSL?

Thanks for considering!

[0]: See https://github.com/rbenv/ruby-build/issues/1353 as an example of Homebrew making changes upstream that broke ruby-build user's ability to install specific ruby versions.

**Comment by mislav** [comment]
> This is a bit puzzling, considering the project opted to _not_ link against Homebrew openssl in #1375.

It's true that we reversed a past decision. I've commented on that directly in my PR:

> We tried this before by always linking to `openssl@1.1`, but that was neither future-proof (today is more common to have `openssl@3` installed) nor backward compatible as it sabotaged installations of older Ruby versions. https://github.com/rbenv/ruby-build/pull/1375

In short, the problems of the past should not be present today because now every Ruby definition defines the range of OpenSSL versions that it is compatible with, and ruby-build uses `brew list` to iterate through every installed version and detect ones that fall under the compatibility range.

> See #1353 as an example of Homebrew making changes upstream that broke ruby-build user's ability to install specific ruby versions.

I appreciate the concern, but this can no longer happen due to the version-compatibility system I've just described. Homebrew can come up with `openssl@4` and `openssl@5` tomorrow, and that won't break installing existing or older Ruby versions.

> I much preferred the prior logic to keep openssl self-contained to the ruby version installed on the system. This prevents a bunch of issues with Homebrew user's (or the project) making changes to brew installed openssl versions that may break their ruby installs

If there are still some concrete issues with Homebrew that could compromise Ruby installs (apart from the one I directly addressed above), I'd love to hear about them. In the meantime, since Homebrew is a de-facto standard package manager on macOS and a preferred package manager for some Linux folks, I've decided to treat Homebrew-installed OpenSSL versions as "system" versions. Normally, compiling Ruby would automatically link it to the system version of OpenSSL that the build system finds in search paths. Now that logic is extended to searching Homebrew-managed paths too. I hope this doesn't prove to be controversial. Let me know please!

**Comment by dentarg** [comment]
I think a nice side-effect of the past behaviour was that using `ruby-build` didn't force an install of `openssl` from Homebrew, so if you hadn't installed it for other reasons, you could continue to use your system `openssl` for CLI things (without fiddling with paths/shell config).

**Comment by mislav** [comment]
> I think a nice side-effect of the past behaviour was that using `ruby-build` didn't force an install of `openssl` from Homebrew

It still doesn't force an install of openssl through Homebrew. It uses this logic:

1. If a system OpenSSL is found and is compatible (this is _never_ the case on macOS), ruby-build uses that one;
2. Otherwise, it searches Homebrew-installed openssl for a compatible version;
3. Otherwise, it downloads and compiles an isolated installation of OpenSSL.

So you see, you can still keep having a system OpenSSL version and you never have to install anything through Homebrew. If you _did_ happen to install `openssl` with Homebrew _and_ if the system OpenSSL is incompatible, Homebrew will get used.

**Comment by dentarg** [comment]
That's nice, thanks for clarifying @mislav!

**Comment by mislav** [comment]
I feel like I have directly addressed the concerns brought up by the OP. Unless some concrete issue arises with ruby-build linking Ruby to Homebrew openssl, I am not inclined to add an extra feature or flag to ruby-build. Closing in the meantime.

**Comment by mohamedhafez** [comment]
> It still doesn't force an install of openssl through Homebrew. It uses this logic:
> 
1. > If a system OpenSSL is found and is compatible (this is never the case on macOS), ruby-build uses that one;
2. > Otherwise, it searches Homebrew-installed openssl for a compatible version;
3. > Otherwise, it downloads and compiles an isolated installation of OpenSSL.

@mislav in the case of 1. or 2., when the system or hombrew version of OpenSSL is updated for security issues, our already-installed rubies will automatically get the new version of OpenSSL, correct? Like they are dynamically linked to "whatever the  system/Hombrew Openssl@3 is"?

**Comment by mislav** [comment]
> when the system or hombrew version of OpenSSL is updated for security issues, our already-installed rubies will automatically get the new version of OpenSSL, correct?

Correct
