### ISSUE TITLE
Can we skip installing readline when Ruby version is greater than 3.3.0?

### ISSUE THREAD

**Issue by okuramasafumi** [rbenv/ruby-build#2330]
https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/

> We no longer need to install libraries like libreadline or libedit.

I installed Ruby 3.3.0 with ruby-build and noticed that it uses readline.

```
==> Installing ruby-3.3.0...
ruby-build: using readline from homebrew
ruby-build: using libyaml from homebrew
ruby-build: using gmp from homebrew
-> ./configure "--prefix=$HOME/.rbenv/versions/3.3.0" --with-openssl-dir=/opt/homebrew/opt/openssl@3 --enable-shared --with-readline-dir=/opt/homebrew/opt/readline --with-libyaml-dir=/opt/homebrew/opt/libyaml --with-gmp-dir=/opt/homebrew/opt/gmp --with-ext=openssl,psych,+
-> make -j 10
-> make install
==> Installed ruby-3.3.0 to /Users/okuramasafumi/.rbenv/versions/3.3.0
```

This `--with-readline-dir=/opt/homebrew/opt/readline` can be skipped for Ruby 3.3.0 and greater as far as I understand.

**Comment by mislav** [comment]
Thank you for raising the question. I just want to first clarify that ruby-build never installs any dependencies; it just potentially discovers them elsewhere on the system and enables the Ruby build process to link to them by passing `--with-readline-dir=` to the configure process.

Now the question is, since Ruby 3.3 apparently doesn't need external libreadline, does `--with-readline-dir=` actually have any effect or if it's simply ignored. If it is ignored, then I suggest that ruby-build keeps passing it because it still helps older Ruby versions.

**Comment by hsbt** [comment]
>If it is ignored, then I suggest that ruby-build keeps passing it because it still helps older Ruby versions.

That is. It's better to remove `--with-readline-dir` option from Ruby 3.3. But It's not effect with build process on Ruby 3.3.
