### ISSUE TITLE
`ruby-1.8.7-p375` and `1.9.2-p326` not installable, uses commit id as branch name

### ISSUE THREAD

**Issue by Earlopain** [rbenv/ruby-build#2478]
### Steps to reproduce the behavior

```sh
$ rbenv install 1.8.7-p375
```

I only ran into this because for 1.8, that is the highest available revision. It's easy to just use the one before, which is available as an archive instead. `1.9.2-p326` I only found by searching around, I didn't actually encounter it.

### Expected vs. actual behavior

Installs fine vs install errors

### Logs

```
==> Cloning https://github.com/ruby/ruby.git...
-> git clone --depth 1 --branch dabc90361d1b71fcac4f606eb1eb1fa25c047fd9 https://github.com/ruby/ruby.git ruby-1.8.7-p375
Cloning into 'ruby-1.8.7-p375'...
warning: Could not find remote branch dabc90361d1b71fcac4f606eb1eb1fa25c047fd9 to clone.
fatal: Remote branch dabc90361d1b71fcac4f606eb1eb1fa25c047fd9 not found in upstream origin

BUILD FAILED (EndeavourOS rolling on x86_64 using ruby-build 20241213)
```

**Comment by mislav** [comment]
@hsbt Would you know anything about why these git tags were never pushed to the `ruby/ruby` repo? Ref. #2120

@Earlopain Thanks for reporting. This was surfaced before, but I kinda forgot about it: https://github.com/rbenv/ruby-build/discussions/2255

The issue is three-fold: first that these Ruby versions do not have a tag in the `ruby/ruby` repo, thus they reference a commit by commit SHA. Second is that these releases were never published as official tarballs: https://www.ruby-lang.org/en/downloads/releases/. And lastly, our `install_git` command doesn't support installing from a commit SHA, only branch names, so this is an actual bug we could fix in our repo. This wasn't anywhere near our priorities, since these Ruby versions are ancient, but if anyone wants to take a stab at a PR, it would be very welcome.

**Comment by hsbt** [comment]
>I propose that we remove these build definitions from ruby-build as they don't seem to be buildable nor officially recognized by the Ruby core project.

Agreed. The Ruby core team didn't release them. see

* https://cache.ruby-lang.org/pub/ruby/1.8/
* https://cache.ruby-lang.org/pub/ruby/1.9/

The some committers push that commit after EOL status. We should ignore these versions.

I created https://github.com/rbenv/ruby-build/pull/2479 for that.
