### ISSUE TITLE
rbenv install does not respect session umask

### ISSUE THREAD

**Issue by donaldguy** [rbenv/ruby-build#400]
I came across this fact today working with automated rbenv installation under chef-solo on Ubuntu 12.04 (see: RiotGames/rbenv-cookbook#52 )

But it is easily apparent under OSX with interactive use as well

> bash
> bash-3.2$ cd $(brew --prefix rbenv)
> bash-3.2$ pwd
> /usr/local/opt/rbenv
> bash-3.2$ cd versions
> total 0
> drwxr-xr-x  7 donaldguy  admin  238 Aug 12 15:20 2.0.0-p247
> bash-3.2$ ls -l
> bash-3.2$ umask
> 0022
> bash-3.2$ umask 002
> bash-3.2$ mkdir test
> bash-3.2$ ls -l
> total 0
> drwxr-xr-x  7 donaldguy  admin  238 Aug 12 15:20 2.0.0-p247
> drwxrwxr-x  2 donaldguy  admin   68 Aug 23 18:21 test
> bash-3.2$ rbenv install 2.1.0-dev
> Downloading openssl-1.0.1e.tar.gz...
> -> https://www.openssl.org/source/openssl-1.0.1e.tar.gz
> Installing openssl-1.0.1e...
> 
> Cloning https://github.com/ruby/ruby.git...
> Installing ruby-2.1.0-dev..
> Installed ruby-2.1.0-dev to /usr/local/opt/rbenv/versions/2.1.0-dev
> bash-3.2$ ls -l
> total 0
> drwxr-xr-x  7 donaldguy  admin  238 Aug 12 15:20 2.0.0-p247
> drwxr-xr-x  7 donaldguy  admin  238 Aug 23 18:28 2.1.0-dev
> drwxrwxr-x  2 donaldguy  admin   68 Aug 23 18:21 test
> bash-3.2$ umask
> 0002

I'll grant this could definitely be a ruby/ruby (or autcong?) bug (I can't really distinguish... but I don't really know how ruby-build works), but I thought I'd pass it up the chain to you anyway

**Comment by map7** [comment]
Should we change the line

    find "$PREFIX_PATH" -type d \( -perm -020 -o -perm -002 \) -exec chmod go-w {} \;

to 

    find "$PREFIX_PATH" -type d \( -perm -020 -o -perm -002 \) -exec chmod o-w {} \;

This would at least fix the permissions on the version's directory, I think the rest of the problem seems to be in the build script for ruby itself.

**Comment by moritzschepp** [comment]
I'm also seeing this on a multi-user install.

@mislav, in #903, you are suggesting to see if the function could be dropped altogether. That would also solve #400.

I just ran the test suite on the current master replacing the `fix_directory_permissions` implementation with a no-op. It still passes. I then built ruby 2.4.4 with the no-op and it doesn't produce world-writables in `versions/2.4.4/bin/`. I'd be happy to create a relevant test but can you point me in the right direction why this code was introduced?

**Comment by jasonkarns** [comment]
Commit is here: https://github.com/rbenv/ruby-build/commit/e1b50e68e339fef4172d000c8d5541a3ec8af14b but I don't see any issue or PR with further details. It doesn't appear to have been modified since its introduction.

**Comment by moritzschepp** [comment]
Alright, thanks!

I just built 2.4.4 with the no-op and umask 0000. Then `~/.rbenv/versions/2.4.4` has permissions `rwxrwxrwx` while `~/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/` has `rwxr-xr-x`. So while this particular issue would be fixed, installing gems with a shared group would still not be possible.

I tried to find the place where the ruby Makefile sets the permissions and it seems that https://github.com/ruby/ruby/blob/master/tool/rbinstall.rb is called without any dir-mode which then defaults to prog-mode which is set to 755 by the Makefile. So the permissions look intentional to me and the install process seems to be designed for a single, system-wide install, managed by root. It feels like changing the permissions (reliably) would be beyond the scope of rbenv-build.

I still didn't find the case justifying e1b50e6, perhaps this is relevant for older ruby versions?

**Comment by mislav** [comment]
I have proposed that we remove the `fix_directory_permissions` hack altogether (see associated PR). It's been a long time since and maybe the Bundler warning isn't an issue anymore? Anyway, I vote that we don't try to manually edit any permissions and let the user be in control of them.
