### ISSUE TITLE
Binary packages

### ISSUE THREAD

**Issue by sstephenson** [rbenv/ruby-build#42]
I'd like to add binary package support to ruby-build. I'd guess that most ruby-build installations are on one of two platforms—Mac OS X x86_64 or Linux x86_64—and most people really don't need to compile their own Ruby runtimes. Binary packages would make it much quicker to get up and running.

In order to do this, we'll need a command to build a definition into a temporary directory and make a tarball. We'll also need a way to download and install package tarballs from the internet. This implies having package repository sources, an architecture naming system, and an index of packages with checksums.

**Comment by schlueter** [comment]
Any movement on this?

**Comment by md5** [comment]
@schlueter +!

**Comment by cybertk** [comment]
+1

**Comment by mconigliaro** [comment]
To be honest, I don't even care about getting *your* binaries to work on *my* machines. If there was just a simple way to check for a precompiled version of Ruby before building (e.g. `RUBY_BUILD_BINARY_URL`?), I'd just build my own and host them myself.

**Comment by md5** [comment]
@mconigliaro If you want to do that, you can use `rbenv` by itself and not use `ruby-build` since its purpose is to build Ruby for `rbenv`.

From [the `rbenv` docs](https://github.com/rbenv/rbenv#installing-ruby-versions):

> Alternatively to the `install` command, you can download and compile Ruby manually as a subdirectory of `~/.rbenv/versions/`. An entry in that directory can also be a symlink to a Ruby version installed elsewhere on the filesystem. `rbenv` doesn't care; it will simply treat any entry in the versions/ directory as a separate Ruby version.

**Comment by mconigliaro** [comment]
@md5 oh yeah, that's a good point. I could always just have my config management system download and unpack a set of precompiled versions to `~/.rbenv/versions/`. Thanks!

**Comment by jasonkarns** [comment]
Super old issue, but I just wanted to pop in and say that node-build (direct fork, minimally modified) has added support for installing precompiled binaries. https://github.com/nodenv/node-build/commit/474e872d9acd5cc61c909f58d1521626d8c9d385 (source has been modified slightly since that PR was merged, though)

We grab the system info via:
```
platform(){
  local arch="$(uname -m)"
  local os="$(uname -s | tr '[:upper:]' '[:lower:]')"

  case "$arch" in
    x86_64 | amd64 | i686-64 ) arch=x64 ;;
    i[36]86* | [ix]86pc )      arch=x86 ;;
  esac

  echo "${os}-${arch}"
}
```

And a build definition looks like:
```
binary darwin-x64 "https://nodejs.org/dist/v4.2.1/node-v4.2.1-darwin-x64.tar.gz#658686795fac9669d411ac5c5be2da8159058e386767322d8d8151dcdb4810b9"
binary linux-arm64 "https://nodejs.org/dist/v4.2.1/node-v4.2.1-linux-arm64.tar.gz#05df4aeb8a53798f8b10074600518040fc317f2919f9755aeab57b0aaf7227b0"
binary linux-armv6l "https://nodejs.org/dist/v4.2.1/node-v4.2.1-linux-armv6l.tar.gz#6f29286464efda4a362d9464d82733398b98882051c20c0f190004480b6e506a"
binary linux-armv7l "https://nodejs.org/dist/v4.2.1/node-v4.2.1-linux-armv7l.tar.gz#fb4fbef9306962e800804ab5ba615c06bba28deb4e7a3e945a291dba986ef816"
binary linux-x64 "https://nodejs.org/dist/v4.2.1/node-v4.2.1-linux-x64.tar.gz#e766e387934e17daaad92d0460ed76f756655da62b627a5c9cc07faea4a0b824"
binary linux-x86 "https://nodejs.org/dist/v4.2.1/node-v4.2.1-linux-x86.tar.gz#97b5ccea7044073c87a21bcc4b0762f4a6bd77db9cc958206f684ecdfeb89b1f"
binary sunos-x64 "https://nodejs.org/dist/v4.2.1/node-v4.2.1-sunos-x64.tar.gz#acec44790ff0069620c0fd03945d14b9f97c7ccb0a0450f766a5cbe4a906510b"
binary sunos-x86 "https://nodejs.org/dist/v4.2.1/node-v4.2.1-sunos-x86.tar.gz#d7bf8dcf353115b5e55bf64d25c2c34fa2d237e201e46dab97ae3d8e3f051583"

install_package "node-v4.2.1" "https://nodejs.org/dist/v4.2.1/node-v4.2.1.tar.gz#8861b9f4c3b4db380fcda19a710c0430c3d62d03ee176c64db63eef95a672663"
```

How it works:

The `binary` function is invoked multiple times from the build definition; given the platform and package url. If the binary's platform matches the current system, the package url is saved to a global variable.

Then when `install_package` is invoked, if a global `BINARY_URL` has been set (and the user hasn't forced a compile with `--compile`), it does an `install_package ... copy`.

It's a pretty hacky workflow, and I would love to find a more elegant solution. But it works and, I think, could be adopted for ruby-build.

**Comment by mislav** [comment]
@jasonkarns Thanks for sharing! That's an interesting approach to fetching precompiled binaries.

In my opinion, it's not such a problem to make ruby-build fetch precompiled binaries as it is to make a system to package and publish precompiled binaries in the first place.

**Comment by koenpunt** [comment]
Travis actually has precompiled rubies: http://rubies.travis-ci.org

**Comment by jtmkrueger** [comment]
This seems kind of dead, and I think that may be partially in part to the desire to make this an "all in one" solution. I think a great first step would be to allow binary installs, but not host them. Require the command to specify the binary location. That way, people can host their own binaries, and reference the location.

**Comment by AlexWayfer** [comment]
No progress here? Or any new ideas?

**Comment by wlnirvana** [comment]
any update?

**Comment by rafaelsales** [comment]
Any progress? RVM makes ruby binaries for ages and it's just fine

**Comment by mislav** [comment]
No progress yet. Anyone is welcome to pick this up!

Some notes:
- [how rvm builds "movable" ruby](https://github.com/rvm/rvm/blob/0233c51c9d8ca9e229833dac5f232b500d3e86e5/scripts/functions/build_config#L32)
- [how Travis builds them](https://github.com/travis-ci/travis-rubies/blob/71625b0b03545185059b7596c1346b8770e34940/build.sh#L229) (uses rvm)
- how we would build them, in theory:
  1. In our CI, use build flags to make rubies "movable",
  1. (Non-critical) strip unnecessary files from the resulting build,
  2. Upload packaged binaries up to S3,
  3. On the user end, allow an opt-in flag `ruby-build --binary 2.6.5 /path/to/destination` that first tries to download and extract pre-build binaries,
  4. Eventually, if all this process yields stable result, enable `--binary` flag by default so everyone can benefit from fast Ruby installs on supported platforms (probably macOS plus several propular Linux distros).

**Comment by mattes** [comment]
> Upload packaged binaries up to S3

Can we re-use http://rvm.io/binaries (cached by [fastly](https://www.fastly.com/)). Unless someone else wants to pay for the S3 traffic :-)

**Comment by technicalpickles** [comment]
Posted this on a duplicate https://github.com/rbenv/ruby-build/issues/1054 :

> GitHub packages is an option now too. Homebrew recently moved to it from bintray recently.

That doesn't address building the packages though.

Some notes from reading through about how RVM does it:

- rvm has a `--movable` flag
- it's documented at https://github.com/rvm/rvm/blob/35e894c7070eaabc38d91220f6e26d1585a7098a/help/install.md#movable-rubies
- there is logic for checking which environments and ruby versions can be built movable: https://github.com/rvm/rvm/blob/35e894c7070eaabc38d91220f6e26d1585a7098a/scripts/functions/build_config#L32-L77
- when it comes to building:
  - on macos, there's a patch applied for static building, and a set of configure flags
  - otherwise there's a configure flag (`--enable-load-relative`)

**Comment by technicalpickles** [comment]
Some more thoughts after the initial work and some time to think...

I'm considering if there should be a separate command for the fetch binary ruby from source or not. I'm also thinking through how we'd do checksums on the tarballs.

For hosting of them, homebrew recently moved from bintray to GitHub Packages. It uses [skopeo](https://github.com/containers/skopeo) to work with remote images registries (which GitHub Packages is), like retrieving information, images, signing content. I'm not sure how they are building the tarballs to publish yet though.

The big question there for me is how to organize things, and how to automate building of the various versions. My initial thought is like:

- add a 'package' for each ruby+version combo on the `rbenv` org, ie `ruby/3.0.1`
- use a timestamp and/or sha of ruby-build for to allow rebuilding when there's an update
   - I don't think they always need to be rebuilt, but I suspect it will be necessary to push an update if there's a bug in `ruby-build`. I don't know how to manage that without requiring always building (and thus always having updates) or manually doing it

Something I'd like to enable as well is to allow organizations to be publishing their own builds, like if they have custom patches or configuration flags they use. This would also give the option to experiment with this before having a working solution for the hosting side of things.

**Comment by wlnirvana** [comment]
Any update on this? Ten years have passed since this issues is raised🤦

**Comment by eregon** [comment]
It's pretty hard and fragile to create movable CRuby builds, see https://github.com/rbenv/ruby-build/pull/1761#issuecomment-857565087
So basically binary builds of CRuby are a problem, they need to be at least (OS, OS version, C compiler path, system libssl version, architecture, destination path and probably more)-specific.
And since `ruby-build` allows installing to any path it could only use those if it's all matching.

IMHO it's fast enough and more reliable to build from source.
If the user's setup is messed up for compilation it won't work when installing C extensions anyway.

**Comment by aleksandrs-ledovskis** [comment]
It would definitely be a bonus if "ruby-build" provides pre-built packages for multitude of aforementioned OS runtime combinations. However, the situation 10 years ago vs. today is quite different with widespread proliferation and usage of containers which subsequently reduces a need to have precompiled interpeters for OP's stated use case "[b]inary packages would make it much quicker to get up and running".
