### ISSUE TITLE
Install Ruby 2.3.0

### ISSUE THREAD

**Issue by solyaris** [rbenv/ruby-build#861]
Hi 
I'd like to install last Ruby version 2.3.0
( https://github.com/rbenv/ruby-build/releases/tag/v20151225 )

$ rbenv install --list | grep 
  2.3.0-dev
  rbx-2.3.0

$ rbenv --version
rbenv 1.0.0-9-ga95ccd0

So I'd like to install the final 2.3.0 (and not previous 2.3.0-dev)
there is a way ?
thanks for your patience
giorgio

**Comment by mislav** [comment]
Could you perhaps try updating ruby-build plugin before trying again?

```
$ rbenv install 2.3.0
ruby-build: definition not found: 2.3.0

The following versions contain `2.3.0' in the name:
  2.3.0-dev
  rbx-2.3.0

See all available versions with `rbenv install --list'.

If the version you need is missing, try upgrading ruby-build:

  cd /Users/mislav/.rbenv/plugins/ruby-build && git pull && cd -
```

**Comment by solyaris** [comment]
Thanks @mislav !
That's solved ! please close and sorry

just a note: maybe is my git-ignorance: 
to update rbenv functionalities and related plugins (ruby-build)
I have to do periodically a git pull; that's correct  ?

cheers
giorgio

**Comment by dideler** [comment]
Upgrading ruby-build was not working for me.
```
$ rbenv install 2.3.0
ruby-build: definition not found: 2.3.0

The following versions contain `2.3.0' in the name:
  2.3.0-dev
  rbx-2.3.0

See all available versions with `rbenv install --list'.

If the version you need is missing, try upgrading ruby-build:

  brew update && brew upgrade ruby-build

$ brew update; and brew upgrade ruby-build
Already up-to-date.
Error: ruby-build HEAD already installed
```

Reinstalling from HEAD worked.
```
$ brew reinstall --HEAD ruby-build
```

**Comment by mislav** [comment]
@dideler I'm glad you solved it, but if you want to upgrade ruby-build in the future via Homebrew, you should do `brew uninstall ruby-build; brew install ruby-build` and not use `--HEAD`. This is because `--HEAD` installs can't be updated via `brew upgrade`.

@solyaris You could have closed the issue yourself as well :wink: Yes, to upgrade rbenv and ruby-build, if you installed via git clone, you'll periodically have to update via `git pull`, especially ruby-build which often has releases.

**Comment by dideler** [comment]
Thanks for the tip @mislav!

**Comment by Nigmatulin** [comment]
Hello, I'm having the same problem. 
I already did `rbenv install 2.3.0` and it was successfully installed. So i ran `rbenv versions` and the result are:
  `* system  (set by /home/eduardo/.rbenv/versions/.ruby-version)`
 `2.3.0`
 So, I ran `rbenv local 2.3.0` and `rbenv global 2.3.0` and the result, after the command versions, are:
  `system`
 `* 2.3.0  (set by /home/eduardo/.rbenv/versions/.ruby-version)`
But, when I ran the command `ruby -v`, the result are:
`ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]`

I want to use the latest version of ruby.

**Comment by iamYPD** [comment]
@Nigmatulin did you find a solution to this? My rbenv global 2.3.0 not working either

**Comment by dpwildboar** [comment]
i had this happen to me, and what i found was the issue was at one time in the past i had installed rbenv with out brew  and it was using that version vs the one that was installed by brew so you might want to do a 'which rbenv' and or --version and make sure you using the one you expected. 

note: brew for me installed in /usr/local and brew cautions you that rbenv liked to install in ~/.rbenv which was where the old version was.

**Comment by michaelperrygoodman** [comment]
I'm having trouble updating my ruby-build definitions in Debian. The output of `rbenv install --list` only goes as high as 2.2.0-dev. Still trying to figure out how to update this. Installed via `apt-get`.

**Comment by michaelghinrichs** [comment]
@mislav  -> 
> brew uninstall ruby-build; brew install ruby-build and not use --HEAD. This is because --HEAD installs can't be updated via brew upgrade.

^^ this was a fantastic call, I was getting the following error:
```sh
❯ brew reinstall --HEAD ruby-build
==> Reinstalling ruby-build
==> Using the sandbox
==> Cloning https://github.com/rbenv/ruby-build.git
Updating /Users/georgemichael/Library/Caches/Homebrew/ruby-build--git
==> Checking out branch master
This repository contains hooks installed by Overcommit, but the `overcommit` gem is not installed.
Install it with `gem install overcommit`.
Error: Failed to download resource "ruby-build"
Failure while executing: git checkout -q -f master --
```

Uninstalling and reinstalling fixed it for me!
