### ISSUE TITLE
Cannot build Ruby 1.9.3-p194 on Centos 6.7

### ISSUE THREAD

**Issue by shakycode** [rbenv/ruby-build#874]
Hi, I'm using the latest rbenv and ruby-build to try to install an older version of ruby I need for a legacy app.  version 1.9.3-p194.

When I go to run `rbenv install -v 1.9.3-p194` I get this error in the output

```
ossl_pkey_ec.c:816: error: ‘EC_GROUP_new_curve_GF2m’ undeclared (first use in this function)
ossl_pkey_ec.c:816: error: (Each undeclared identifier is reported only once
ossl_pkey_ec.c:816: error: for each function it appears in.)
make[2]: *** [ossl_pkey_ec.o] Error 1
make[1]: *** [ext/openssl/all] Error 2
````
Full pastebin [here](http://pastebin.com/wXJkwFwY)

Upgrading ruby right now in the app is not a viable option, so I'm hoping someone can help with a patch or more information.

**Comment by mislav** [comment]
I'm sorry you're having trouble. Older Rubies often have trouble compiling on new systems, and if you can't find a community-maintained patch that you can apply, sometimes there is nothing you can do.

If your app requires Ruby 1.9.3, you could try to at least upgrade it to `1.9.3-p551`. Maybe a newer patch release will have some build problems fixed, and your app shouldn't break because there shouldn't be feature changes between these versions of Ruby.

**Comment by shakycode** [comment]
@mislav I was able to figure this out and build Ruby 1.9.3-p194 successfully by issuing the following command:

`curl -fsSL "https://github.com/ruby/ruby/commit/0d58bb55985e787364b0235e5e69278d0f0ad4b0.patch" |   filterdiff -x a/ChangeLog | rbenv install --patch -v 1.9.3-p194`

Took me a while to find it and figure it out but so far Ruby is a go.  Thank you so much for following up to quickly. :+1:

**Comment by a-velt** [comment]
Thank you fidid, your solution works for me !
Best,
Amandine
