### ISSUE TITLE
1.8.6-p420 build failed on Ubuntu 10.4 Lucid Lynx

### ISSUE THREAD

**Issue by ipoerner** [rbenv/ruby-build#88]
```
$ rbenv install 1.8.6-p420 
Downloading http://ftp.ruby-lang.org/pub/ruby/1.8/ruby-1.8.6-p420.tar.gz...
Installing ruby-1.8.6-p420...

BUILD FAILED

Inspect or clean up the working tree at /tmp/ruby-build.20111107212352.8310
Results logged to /tmp/ruby-build.20111107212352.8310.log

Last 10 log lines:
/usr/bin/gcc -g -O2  -DRUBY_EXPORT -D_GNU_SOURCE=1  -L. -L'/home/ingmar/.rbenv/versions/1.8.6-p420/lib'  -rdynamic -Wl,-export-dynamic   main.o  libruby-static.a -lrt -ldl -lcrypt -lm   -o miniruby
rbconfig.rb updated
compiling Win32API
compiling bigdecimal
make[1]: Entering directory `/tmp/ruby-build.20111107212352.8310/ruby-1.8.6-p420/ext/bigdecimal'
mkdir -p ../../.ext/i686-linux
make[1]: *** read jobs pipe: No such file or directory.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/tmp/ruby-build.20111107212352.8310/ruby-1.8.6-p420/ext/bigdecimal'
make: *** [all] Error 1
```

It's been suggested that this is a bug in the Ruby Makefiles, but all I know is that omitting '-j 2' from the make call solves the problem for me.

**Comment by ju2wheels** [comment]
Because I racked my head over this for much longer than was necessary, id like to point out to anyone that the instructions above for compiling 1.8.x work great with one downside:

You will not be able to install anything > 1.8.x using rbenv if you have installed openssl 0.9.8 from source because /usr/local will take precedence during compiling even if you remove it from your PATH before running rbenv. So be sure to install higher versions first and come back to 1.8.x after if you need these to coexist on the same machine. There might be some extra options to the compile to make rbenv not pass on /usr/loca/* in the PATH but im not sure what it is if there is one.

**Comment by bhardin** [comment]
Hi @warmwaffles. Had this issue with Jenkins. :)

**Comment by warmwaffles** [comment]
Just recently @bhardin?

**Comment by bhardin** [comment]
Yes. Rebuilding.
