### ISSUE TITLE
Can't install ruby 2.3.0 on debian wheezy

### ISSUE THREAD

**Issue by carloscarcamo** [rbenv/ruby-build#914]
I'm trying to install ruby 2.3.0 on debian wheezy but I got this error:

``` sh
$ rbenv install 2.3.0
Downloading ruby-2.3.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
Installing ruby-2.3.0...

BUILD FAILED (Debian 7.7 using ruby-build 20160228-3-g37b3ded)

Inspect or clean up the working tree at /tmp/ruby-build.20160303160056.5246
Results logged to /tmp/ruby-build.20160303160056.5246.log

Last 10 log lines:
In file included from /usr/include/x86_64-linux-gnu/sys/syscall.h:31:0,
                 from /usr/include/syscall.h:1,
                 from random.c:81:
random.c: In function ‘fill_random_bytes_syscall’:
random.c:541:16: error: ‘__NR_getrandom’ undeclared (first use in this function)
  ret = syscall(SYS_getrandom, seed, size, flags);
                ^
random.c:541:16: note: each undeclared identifier is reported only once for each function it appears in
make: *** [random.o] Error 1
```

Any thoughts?

**Comment by mislav** [comment]
I have never seen this. Have you found a workaround since?

**Comment by carloscarcamo** [comment]
not yet! I don't have idea about this!

**Comment by edumerco** [comment]
Same thing here... Debian Wheezy (Crunchbang Waldorf).

**Comment by ehamon** [comment]
Same issue on Debian Jessie.

**Comment by sergioasantiago** [comment]
:+1:  on Debian Jessie and installing ruby version 2.3.1

**Comment by sabcio** [comment]
Same error on Jessie when installing 2.3.0/2.3.1.

**Comment by sergioasantiago** [comment]
I could only manage to install it, doing an `apt-get upgrade`
Worked after that.

**Comment by ptsampoukas** [comment]
The build fails because it cannot find the getrandom syscall. The getrandom call was introduced in version 3.17 of the Linux kernel (according to its man page). Debian Jessie comes with 3.16, so the build fails.

Ruby 2.3.1 can be compiled with older kernels of course. It tries to compile with getrandom because SYS_getrandom is defined in the file syscall.h. This file is added by the libc6-dev package:

$ apt-file search /usr/include/x86_64-linux-gnu/bits/syscall.h
libc6-dev: /usr/include/x86_64-linux-gnu/bits/syscall.h

For some mysterious reason my system had the wrong file and a package version that is not available for debian Jessie:

$ dpkg -l libc6-dev
...
ii  libc6-dev:amd64   2.19-**19**  amd64    GNU C Library: Development Libraries and Header Files

The latest package version for Jessie is 2.19-**18**+deb8u4. Trying to reinstall the package fails and apt complains it has no way to download the package (the 2.19 version).

The solution for me was to remove the libc6-dev package and reinstall it from deb packages I downloaded manually from the debian site. I then repeated this for libc-dev-bin and finally installed with apt the packages that had to be removed in the process. Ruby 2.3.1 builds now.

**Comment by hsbt** [comment]
I couldn't reproduce Ruby 2.3.1 on debian jessie(8.6). Please try to upgrade Ruby or debian box.

**Comment by TB-Development** [comment]
This isn't a solution to the original problem, but for future readers it might be useful.

I had a similar issue with older versions of ruby not being able to function with newer versions of OpenSSL.  I googled around and found some solutions and was able to successfully install Ruby 2.3.0 on a newer version of Debian Linux(11) from scratch with Docker. 

 Here is how I did it:

```
FROM buildpack-deps:bullseye
RUN apt-get update

# https://github.com/rbenv/ruby-build/wiki#openssl-usrincludeopensslasn1_mach102-error-error-this-file-is-obsolete-please-update-your-software
RUN apt-get install -y autoconf bison patch build-essential rustc libyaml-dev libreadline6-dev zlib1g-dev libgmp-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev uuid-dev rbenv ca-certificates

# https://stackoverflow.com/questions/57946621/error-running-requirements-debian-libs-install-libssl-dev
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
RUN echo "deb http://security.ubuntu.com/ubuntu bionic-security main" >> /etc/apt/sources.list
RUN apt-get update && apt-cache policy libssl1.0-dev && apt-get update
RUN apt-get install -y libssl1.0-dev

### Make rbenv runnable
RUN echo "eval '$(rbenv init -)'" >> ~/.bashrc
RUN rbenv install 2.3.0
```
