### ISSUE TITLE
Unable to install 1.8.7-p375

### ISSUE THREAD

**Issue by sakasita** [rbenv/ruby-build#915]
I tried to install ruby 1.8.7-p375 on CentOS 5.  But it is failed.
```
$ rbenv install 1.8.7-p375
Checking out http://svn.ruby-lang.org/repos/ruby/branches/ruby_1_8_7...

BUILD FAILED (CentOS release 5.11 (Final) using ruby-build 20160111)
```
```
$ rbenv install -l
Available versions:
  1.8.6-p383
(snip)
  1.8.7-p374
  1.8.7-p375
  1.9.1-p378
```
It seems rbenv is support to install 1.8.7-p375.  1.8.7-p374 is OK.

share/ruby-build/1.8.7-p374 use a source of ruby below
> install_package "ruby-1.8.7-p374" "https://cache.ruby-lang.org/pub/ruby/1.8/ruby-1.8.7-p374.tar.bz2#b4e34703137f7bfb8761c4ea474f7438d6ccf440b3d35f39cc5e4d4e239c07e3" auto_tcltk standard

And share/ruby-build/1.8.7-p375 use below
> install_svn "ruby-1.8.7-p375" "http://svn.ruby-lang.org/repos/ruby/branches/ruby_1_8_7" "44351" autoconf auto_tcltk standard

I hope to fix to build it or remove 1.8.7-p375 from the list.

**Comment by mislav** [comment]
Since Ruby 1.8.7 p375 was never tagged in their version control, we have to resort to pulling it down via svn. Perhaps the installation failed because you need to install SVN first, and you were able to install other versions because they don't need SVN.

In any case, we can't know more until you share with us the full build log (you only shared with us the parital build output). The full log is stored in a reference file.

I hope this advice helps you work around this! Good luck.
